spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/prex_db
    username: postgres
    password: postgres
  security:
    user:
      password: 1801

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    env:
      enabled: true
    info:
      enabled: true

logging:
  level:
    web: debug
  pattern:
    console: "%clr(%d{dd-MM-yy HH:mm:ss}){faint} %clr(%5p) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

custom:
  properties:
    remember:
      key: all_the_things_ive_done