spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.3.35:32768/plh_db
    username: postgres
    password: postgrespw
  security:
    user:
      password: 1801
  servlet:
    multipart:
      max-request-size: 15MB
      max-file-size: 2MB

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    env:
      enabled: true
    info:
      enabled: true

logging:
#  level:
  #    web: debug
  pattern:
    console: "%clr(%d{dd-MM-yy HH:mm:ss}){faint} %clr(%5p) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

custom:
  properties:
    remember:
      key: all_the_things_ive_done